"""add discount fields to products

Revision ID: 069fb6517e5f
Revises: 9c9c1f827f11
Create Date: 2026-06-22 10:37:49.442808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '069fb6517e5f'
down_revision: Union[str, Sequence[str], None] = '9c9c1f827f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('discount_percent', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('discount_starts_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('discount_ends_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'discount_ends_at')
    op.drop_column('products', 'discount_starts_at')
    op.drop_column('products', 'discount_percent')
    # ### end Alembic commands ###
