"""add brand and available_sizes to products

Revision ID: 9c9c1f827f11
Revises: f30cf1eb1a1c
Create Date: 2026-06-20 16:16:23.864519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c9c1f827f11'
down_revision: Union[str, Sequence[str], None] = 'f30cf1eb1a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_addresses_user_id'), table_name='addresses')
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.add_column('products', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('products', sa.Column('available_sizes', sa.String(), nullable=True))
    op.drop_index(op.f('ix_products_category_stock'), table_name='products')
    op.drop_index(op.f('ix_products_in_stock'), table_name='products')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_products_in_stock'), 'products', ['in_stock'], unique=False)
    op.create_index(op.f('ix_products_category_stock'), 'products', ['category_id', 'in_stock'], unique=False)
    op.drop_column('products', 'available_sizes')
    op.drop_column('products', 'brand')
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    # ### end Alembic commands ###
